### ISSUE TITLE
Learning `.bind` before learning `this`?

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/javascript-first-class-functions-lab#9]
From the linked resources: 

"We use the Bind () method primarily to call a function with the _this_ value set explicitly. ... Before we look at the code for this section, we should understand the _this_ keyword in JavaScript. ...  If you don’t understand _this_ well, you will have trouble understanding some of the concepts discussed below."

_This_ has yet to be introduced in the curriculum, so introducing `.bind` is extremely confusing.

**Comment by itzsaga** [comment]
I believe the readme takes care of this confusion:
> Quick hint: you can forget about `.bind()`'s first argument (the `this` context) for now — you can use `null` as its value.

In addition, the MDN doc linked has the section [Partially applied functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind#Partially_applied_functions) which illustrates exactly what we need to do.

I liked this small curveball. It wasn't too difficult to figure out IMO.

**Comment by gj** [comment]
Continuing the trend of commenting on the 27th of each month...

I hear your concerns about dealing with a core concept (`this`) that hasn't yet been introduced, but I agree with @itzsaga that the `Quick hint` is enough of a tip to get students through the lesson. You'll encounter `bind` again after you've learned about `this`... fear not!
